# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.

[tox]
envlist =
    py38,
    py39,
    py310,
    py311,
    py312,
    py313,
    py314,
    doc,

[testenv]
commands =
    {envbindir}/pytest {posargs}

deps =
    pytest
    lxml

[testenv:doc]
changedir = doc
setenv = APIDOC=True

deps =
    sphinx
    pytest
    sphinx_rtd_theme
commands =
    sphinx-build -q -d {envtmpdir}/doctrees . {envtmpdir}/html


[testenv:cov]
passenv =
    COVERALLS_REPO_TOKEN
    GIT_*
deps =
    {[testenv]deps}
    pytest-cov
    coveralls
commands =
    pytest -qq --cov=et_xmlfile --cov-report=term-missing --cov-report=xml
    coveralls
